# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()
## The editor (and arguments) to use for the `open-editor` command. `{}`
c.editor.command = ['gvim', '-f', '{}']
## Encoding to use for the editor.
c.editor.encoding = 'utf-8'
config.bind('<Ctrl-E>', 'open-editor', mode='insert')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# List of user stylesheet filenames to use.
# Type: List of File, or File
c.content.user_stylesheets = []

# Bindings for normal mode
config.bind(',n', 'config-cycle content.user_stylesheets ~/.config/qutebrowser/solarized.css ""')
config.bind('M', 'hint links spawn mpv {hint-url}')
config.bind('m', 'spawn mpv {url}')
c.url.searchengines = {
        'DEFAULT': 
'https://duckduckgo.com/?q={}',
        'i': 
'https://duckduckgo.com/?q={}&iar=images&iax=images&ia=images',
        'vic': 
'https://la.wikipedia.org/w/index.php?search={}&title=Specialis%3AQuaerere',
        'red': 
'https://reddit.com/r/{}',
        'wt': 
'http://en.wiktionary.org/?search={}',
        'osm': 
'http://www.openstreetmap.org/search?query={}',
        'art': 
'http://arizona.summon.serialssolutions.com/search?q={}',
        'book': 
'http://sabio.library.arizona.edu/search/X?SEARCH={}',
        'lib': 
'http://gen.lib.rus.ec/search.php?req={}',
        'tpb': 
'http://thepiratebay.org/search/{}',
        'laincat': 
'http://lainchan.org/{}/catalog.html',
        'tw': 
'https://twitter.com/{}',
        '8': 'https://8ch.net/{}',
        'eb': 
'https://ebay.com/sch/{}',
        'etym': 
'http://etymonline.com/index.php?allowed_in_frame=0&search={}',
        'ddg': 
'https://duckduckgo.com/?q={}&t=ha&iar=images',
        'aw': 
'https://wiki.archlinux.org/index.php?title=Special%3ASearch&search={}',
        '4cat': 
'https://boards.4chan.org/{}/catalog',
        'lain': 
'http://lainchan.org/{}',
        'gw': 
'https://wiki.gentoo.org/index.php?title=Special%3ASearch&search={}',
        '8cat': 
'https://8ch.net/{}/catalog.html',
        'yt': 
'https://www.youtube.com/results?search_query={}',
        'ig': 
'https://wiki.installgentoo.com/index.php?search={}&title=Special%3ASearch',
        'w': 
'https://www.wikipedia.org/search-redirect.php?family=wikipedia&language=en&search={}&language=en&go=Go',
        '4': 
'https://boards.4chan.org/{}',
        'sk': 
'https://www.skytorrents.in/search/all/ed/1/?l=en-us&q={}',
        'vw': 
'https://wiki.voidlinux.eu/index.php?search={}&title=Special%3ASearch',
        'thw': 
'http://www.thinkwiki.org/w/index.php?search={}&title=Special%3ASearch',
        'vw': 
'http://vim.wikia.com/wiki/Special:Search?fulltext=Search&query={}',
        'bc': 
'https://www.bitchute.com/search?q={}&sort=date_created%20desc',
        'mdbg': 
'https://mdbg.net/chinese/dictionary?page=worddict&wdrst=0&wdqb={}',
        }
